# Generated by Django 3.2.13 on 2022-06-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio', verbose_name='Fec. ini.')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin', verbose_name='Fec. fin.')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'peri',
            },
        ),
    ]
